# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: 'da404ac2-a919-45ee-a22c-af80a12032af'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'AzureRmPipeline-rg'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/MS-binche/AzureRmPipeline-repo/master/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName testproject'
    deploymentMode: 'Incremental'
    deploymentName: 'deploypipelinetemplate'